import mockjs from 'mockjs';
const outPutList = {
  code: 200,
  message: '操作成功',
  data: [
    {
      id: 1,
      key: 1,
      name: '过滤器',
      specification: 'FLR01917',
      'count|1-10': 1,
      unit: '个',
      'price|1-1000': 1,
      systemName: '空调及机械通风系统',
      deviceTypeName: '冷冻主机',
    },
    {
      id: 2,
      key: 2,
      name: '22',
      specification: '23',
      'count|1-10': 23,
      unit: null,
      'price|1-1000': 2,
      brand: null,
      lowerWarningStock: 2,
      systemName: '空调及机械通风系统',
      deviceTypeName: '冷冻主机',
    },
    {
      id: 3,
      key: 3,
      name: '过滤器',
      specification: null,
      'count|1-10': 10,
      unit: null,
      'price|1-1000': 1,
      brand: null,
      lowerWarningStock: 11,
      systemName: '空调及机械通风系统',
      deviceTypeName: '冷冻主机',
    },
    {
      id: 4,
      key: 4,
      name: '轴承',
      specification: null,
      'count|1-10': 0,
      unit: '个',
      'price|1-1000': 0,
      systemName: '空调及机械通风系统',
      deviceTypeName: '冷冻水泵',
    },
    {
      id: 5,
      key: 5,
      name: 'O型密封圈',
      specification: null,
      'count|1-10': 0,
      unit: '套',
      'price|1-1000': 0,
      systemName: '空调及机械通风系统',
      deviceTypeName: '冷冻水泵',
    },
    {
      id: 6,
      key: 6,
      name: '机械密封',
      specification: null,
      'count|1-10': 0,
      unit: '套',
      'price|1-1000': 0,
      systemName: '空调及机械通风系统',
      deviceTypeName: '冷冻水泵',
    },
    {
      id: 7,
      key: 7,
      name: '良机LRC-H-900散热片（系统一）',
      specification: '0.35×320×800mm',
      'count|1-10': 0,
      unit: '片',
      'price|1-1000': 0,
      systemName: '空调及机械通风系统',
      deviceTypeName: '冷却水塔（系统一）',
    },
    {
      id: 8,
      key: 8,
      name: '马利水塔NC8413 S-1散热片（系统二）',
      specification: '1524×3086×0.32mm',
      'count|1-10': 0,
      unit: '片',
      'price|1-1000': 0,
      systemName: '空调及机械通风系统',
      deviceTypeName: '冷却水塔（系统二）',
    },
    {
      id: 9,
      key: 9,
      name: '轴承',
      specification: null,
      'count|1-10': 0,
      unit: '个',
      'price|1-1000': 0,
      systemName: '空调及机械通风系统',
      deviceTypeName: '冷凝水泵',
    },
    {
      id: 10,
      key: 10,
      name: 'O型密封圈',
      specification: null,
      'count|1-10': 0,
      unit: '套',
      'price|1-1000': 0,
      systemName: '空调及机械通风系统',
      deviceTypeName: '冷凝水泵',
    },
    {
      id: 11,
      key: 11,
      name: '机械密封',
      specification: null,
      'count|1-10': 0,
      unit: '套',
      'price|1-1000': 0,
      systemName: '空调及机械通风系统',
      deviceTypeName: '冷凝水泵',
    },
    {
      id: 12,
      key: 12,
      name: '轴承',
      specification: null,
      'count|1-10': 0,
      unit: null,
      'price|1-1000': 0,
      systemName: '空调及机械通风系统',
      deviceTypeName: 'AHU风柜',
    },
    {
      id: 13,
      key: 13,
      name: '水机械密塞',
      specification: null,
      'count|1-10': 0,
      unit: null,
      'price|1-1000': 0,
      systemName: '空调及机械通风系统',
      deviceTypeName: 'AHU风柜',
    },
    {
      id: 14,
      key: 14,
      name: '皮带',
      specification: null,
      'count|1-10': 0,
      unit: null,
      'price|1-1000': 0,
      deviceTypeName: 'AHU风柜',
    },
  ],
};
export default {
  'GET /toolManager/outPutList': mockjs.mock(outPutList),
};
