<<<<<<< HEAD
const deviceBasicList = [
  {
    "id": 1,
    "sn": "CH-1",
    "name": "冷冻主机-1",
    "model": "CVHG780-489-287-T080S-800-T080L-800",
    "position": "13区 2F ",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2006-07-10",
    "status": 1
  },
  {
    "id": 2,
    "sn": "CH-2",
    "name": "冷冻主机-2",
    "model": "CVHG780-489-287-T080S-800-T080L-800",
    "position": "13区 2F ",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2006-07-10",
    "status": 1
  },
  {
    "id": 3,
    "sn": "CH-3",
    "name": "冷冻主机-3",
    "model": "CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0",
    "position": "6-1区 GF层0-091",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2013年",
    "status": 1
  },
  {
    "id": 4,
    "sn": "CH-4",
    "name": "冷冻主机-4",
    "model": "CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0",
    "position": "6-1区 GF层0-091",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2013年",
    "status": 1
  },
  {
    "id": 5,
    "sn": "CH-5",
    "name": "冷冻主机-5",
    "model": "CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0",
    "position": "6-1区 GF层0-091",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2013年",
    "status": 1
  },
  {
    "id": 6,
    "sn": "CH-6",
    "name": "冷冻主机-6",
    "model": "CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0",
    "position": "6-1区 GF层0-091",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2013年",
    "status": 1
  },
  {
    "id": 7,
    "sn": "CH-7",
    "name": "冷冻主机-7",
    "model": "CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0",
    "position": "6-1区 GF层0-091",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2013年",
    "status": 1
  },
  {
    "id": 8,
    "sn": "CHWP-01",
    "name": "冷冻水泵-1",
    "model": "TD150-400",
    "position": "13区 2F ",
    "deviceTypeName": "冷冻水泵",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Elektrim",
    "productDate": "2006年",
    "status": 1
  },
  {
    "id": 9,
    "sn": "CH-1",
    "name": "冷冻主机-1",
    "model": "CVHG780-489-287-T080S-800-T080L-800",
    "position": "13区 2F ",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2006-07-10",
    "status": 1
  },
  {
    "id": 10,
    "sn": "CH-2",
    "name": "冷冻主机-2",
    "model": "CVHG780-489-287-T080S-800-T080L-800",
    "position": "13区 2F ",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2006-07-10",
    "status": 1
  },
  {
    "id": 11,
    "sn": "CH-3",
    "name": "冷冻主机-3",
    "model": "CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0",
    "position": "6-1区 GF层0-091",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2013年",
    "status": 1
  },
  {
    "id": 12,
    "sn": "CH-4",
    "name": "冷冻主机-4",
    "model": "CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0",
    "position": "6-1区 GF层0-091",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2013年",
    "status": 1
  },
  {
    "id": 13,
    "sn": "CH-5",
    "name": "冷冻主机-5",
    "model": "CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0",
    "position": "6-1区 GF层0-091",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2013年",
    "status": 1
  },
  {
    "id": 14,
    "sn": "CH-6",
    "name": "冷冻主机-6",
    "model": "CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0",
    "position": "6-1区 GF层0-091",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2013年",
    "status": 1
  },
  {
    "id": 15,
    "sn": "CH-7",
    "name": "冷冻主机-7",
    "model": "CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0",
    "position": "6-1区 GF层0-091",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2013年",
    "status": 1
  },
  {
    "id": 16,
    "sn": "CHWP-01",
    "name": "冷冻水泵-1",
    "model": "TD150-400",
    "position": "13区 2F ",
    "deviceTypeName": "冷冻水泵",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Elektrim",
    "productDate": "2006年",
    "status": 1
  },
  {
    "id": 17,
    "sn": "CH-1",
    "name": "冷冻主机-1",
    "model": "CVHG780-489-287-T080S-800-T080L-800",
    "position": "13区 2F ",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2006-07-10",
    "status": 1
  },
  {
    "id": 18,
    "sn": "CH-2",
    "name": "冷冻主机-2",
    "model": "CVHG780-489-287-T080S-800-T080L-800",
    "position": "13区 2F ",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2006-07-10",
    "status": 1
  },
  {
    "id": 19,
    "sn": "CH-3",
    "name": "冷冻主机-3",
    "model": "CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0",
    "position": "6-1区 GF层0-091",
    "deviceTypeName": "冷冻主机",
    "systemName": "空调及机械通风系统",
    "areaName": null,
    "productFactory": "Trane",
    "productDate": "2013年",
    "status": 1
  }
]
const deviceKeepList = [
  {
    "id": 1,
    "name": "主机运行模式",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 0,
    "option": "本控/中央控",
    "unit": "N/A",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 2,
    "name": "设备状态",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 0,
    "option": "运行/停止/故障",
    "unit": "N/A",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 3,
    "name": "阀门运行模式",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 0,
    "option": "手动/自动/关闭",
    "unit": "N/A",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 4,
    "name": "当前冰水运行设定值",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "℃",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 5,
    "name": "电流",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "A",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 6,
    "name": "电压",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "V",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 7,
    "name": "压缩机运行RLA",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "％",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 8,
    "name": "运行功率",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "KW",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 9,
    "name": "蒸发器进水温度",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "℃",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 10,
    "name": "蒸发器出水温度",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "℃",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 11,
    "name": "蒸发器冷媒饱和温度",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "℃",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 12,
    "name": "蒸发器冷媒压力",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "kPa",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 13,
    "name": "冷凝器进水温度",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "℃",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 14,
    "name": "冷凝器出水温度",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "℃",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 15,
    "name": "冷凝器冷媒饱和温度",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "℃",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  },
  {
    "id": 16,
    "name": "冷凝器冷媒趋近温度",
    "systemName": "空调及机械通风系统",
    "period": "1",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "℃",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null
  }
]
const deviceCheckList = [
  {
    "id": 1,
    "systemId": 1,
    "deviceTypeId": 1,
    "name": "设备状态",
    "systemName": "空调及机械通风系统",
    "period": "0",
    "checkMethod": "目测",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 0,
    "option": "运行/停止/故障",
    "unit": "N/A",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null,
    "minValue": null,
    "maxValue": null
  },
  {
    "id": 2,
    "systemId": 1,
    "deviceTypeId": 1,
    "name": "主机运行模式",
    "systemName": "空调及机械通风系统",
    "period": "0",
    "checkMethod": "记录设备显示",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 0,
    "option": "本控/中央控",
    "unit": "N/A",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null,
    "minValue": null,
    "maxValue": null
  },
  {
    "id": 3,
    "systemId": 1,
    "deviceTypeId": 1,
    "name": "阀门运行模式",
    "systemName": "空调及机械通风系统",
    "period": "0",
    "checkMethod": "记录设备显示",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 0,
    "option": "手动/自动/关闭",
    "unit": "N/A",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null,
    "minValue": null,
    "maxValue": null
  },
  {
    "id": 4,
    "systemId": 1,
    "deviceTypeId": 1,
    "name": "当前冻水设定值",
    "systemName": "空调及机械通风系统",
    "period": "0",
    "checkMethod": "记录设备显示",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "℃",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null,
    "minValue": null,
    "maxValue": null
  },
  {
    "id": 5,
    "systemId": 1,
    "deviceTypeId": 1,
    "name": "电压",
    "systemName": "空调及机械通风系统",
    "period": "0",
    "checkMethod": "记录设备显示",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "V",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null,
    "minValue": null,
    "maxValue": null
  },
  {
    "id": 6,
    "systemId": 1,
    "deviceTypeId": 1,
    "name": "电流-R",
    "systemName": "空调及机械通风系统",
    "period": "0",
    "checkMethod": "记录设备显示",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "A",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null,
    "minValue": null,
    "maxValue": null
  },
  {
    "id": 7,
    "systemId": 1,
    "deviceTypeId": 1,
    "name": "电流-S",
    "systemName": "空调及机械通风系统",
    "period": "0",
    "checkMethod": "记录设备显示",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "A",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null,
    "minValue": null,
    "maxValue": null
  },
  {
    "id": 8,
    "systemId": 1,
    "deviceTypeId": 1,
    "name": "电流-T",
    "systemName": "空调及机械通风系统",
    "period": "0",
    "checkMethod": "记录设备显示",
    "deviceTypeName": "冷冻主机",
    "areaName": null,
    "type": 1,
    "option": null,
    "unit": "A",
    "standardDesc": null,
    "imageUrl": null,
    "remark": null,
    "minValue": null,
    "maxValue": null
  }
]
const deviceContextList = [
  {
    "id": 37,
    "systemId": null,
    "deviceTypeId": null,
    "name": "过滤器",
    "specification": "FLR01917",
    "count": 0,
    "totalInStockCount": 0,
    "unit": "个",
    "price": null,
    "brand": null,
    "lowerWarningStock": null,
    "remark": null,
    "createTime": null,
    "updateTime": null,
    "createBy": null,
    "updateBy": null,
    "systemName": "空调及机械通风系统",
    "deviceTypeName": "冷冻主机"
  },
  {
    "id": 127,
    "systemId": null,
    "deviceTypeId": null,
    "name": "22",
    "specification": "23",
    "count": 23,
    "totalInStockCount": 0,
    "unit": null,
    "price": 2,
    "brand": null,
    "lowerWarningStock": 2,
    "remark": null,
    "createTime": null,
    "updateTime": null,
    "createBy": null,
    "updateBy": null,
    "systemName": "空调及机械通风系统",
    "deviceTypeName": "冷冻主机"
  },
  {
    "id": 128,
    "systemId": null,
    "deviceTypeId": null,
    "name": "过滤器",
    "specification": null,
    "count": 10,
    "totalInStockCount": 0,
    "unit": null,
    "price": 1,
    "brand": null,
    "lowerWarningStock": 11,
    "remark": null,
    "createTime": null,
    "updateTime": null,
    "createBy": null,
    "updateBy": null,
    "systemName": "空调及机械通风系统",
    "deviceTypeName": "冷冻主机"
  },
  {
    "id": 38,
    "systemId": null,
    "deviceTypeId": null,
    "name": "轴承",
    "specification": null,
    "count": 0,
    "totalInStockCount": 0,
    "unit": "个",
    "price": null,
    "brand": null,
    "lowerWarningStock": null,
    "remark": null,
    "createTime": null,
    "updateTime": null,
    "createBy": null,
    "updateBy": null,
    "systemName": "空调及机械通风系统",
    "deviceTypeName": "冷冻水泵"
  },
  {
    "id": 39,
    "systemId": null,
    "deviceTypeId": null,
    "name": "O型密封圈",
    "specification": null,
    "count": 0,
    "totalInStockCount": 0,
    "unit": "套",
    "price": null,
    "brand": null,
    "lowerWarningStock": null,
    "remark": null,
    "createTime": null,
    "updateTime": null,
    "createBy": null,
    "updateBy": null,
    "systemName": "空调及机械通风系统",
    "deviceTypeName": "冷冻水泵"
  },
  {
    "id": 40,
    "systemId": null,
    "deviceTypeId": null,
    "name": "机械密封",
    "specification": null,
    "count": 0,
    "totalInStockCount": 0,
    "unit": "套",
    "price": null,
    "brand": null,
    "lowerWarningStock": null,
    "remark": null,
    "createTime": null,
    "updateTime": null,
    "createBy": null,
    "updateBy": null,
    "systemName": "空调及机械通风系统",
    "deviceTypeName": "冷冻水泵"
  },
  {
    "id": 44,
    "systemId": null,
    "deviceTypeId": null,
    "name": "良机LRC-H-900散热片（系统一）",
    "specification": "0.35×320×800mm",
    "count": 0,
    "totalInStockCount": 0,
    "unit": "片",
    "price": null,
    "brand": null,
    "lowerWarningStock": null,
    "remark": null,
    "createTime": null,
    "updateTime": null,
    "createBy": null,
    "updateBy": null,
    "systemName": "空调及机械通风系统",
    "deviceTypeName": "冷却水塔（系统一）"
  },
  {
    "id": 45,
    "systemId": null,
    "deviceTypeId": null,
    "name": "马利水塔NC8413 S-1散热片（系统二）",
    "specification": "1524×3086×0.32mm",
    "count": 0,
    "totalInStockCount": 0,
    "unit": "片",
    "price": null,
    "brand": null,
    "lowerWarningStock": null,
    "remark": null,
    "createTime": null,
    "updateTime": null,
    "createBy": null,
    "updateBy": null,
    "systemName": "空调及机械通风系统",
    "deviceTypeName": "冷却水塔（系统二）"
  }
]
const toolContextList = [
  {
    "id": 1,
    "name": "木工修边机",
    "specification": "MT370",
    "count": 1,
    "unit": "台",
    "brand": null,
    "remark": null,
    "createTime": "2019-10-08 16:53:04",
    "updateTime": null,
    "createBy": null,
    "updateBy": null
  },
  {
    "id": 2,
    "name": "手电鑽",
    "specification": "GBM10RE",
    "count": 12,
    "unit": "把",
    "brand": null,
    "remark": null,
    "createTime": "2019-10-08 16:53:29",
    "updateTime": "2019-10-15 14:43:45",
    "createBy": null,
    "updateBy": null
  },
  {
    "id": 3,
    "name": "扳手",
    "specification": "GBM10RE",
    "count": 12,
    "unit": "把",
    "brand": null,
    "remark": null,
    "createTime": "2019-10-08 16:53:29",
    "updateTime": "2019-10-15 14:43:45",
    "createBy": null,
    "updateBy": null
  }
]
export default {
  'GET /standing/deviceBasicList': deviceBasicList,
  'GET /standing/deviceCheckList': deviceCheckList,
  'GET /standing/deviceKeepList': deviceKeepList,
  'GET /standing/deviceContextList': deviceContextList,
  'GET /standing/toolContextList': toolContextList,
}
=======
const deviceBasicList = [
  {
    id: 1,
    sn: 'CH-1',
    name: '冷冻主机-1',
    model: 'CVHG780-489-287-T080S-800-T080L-800',
    position: '13区 2F ',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2006-07-10',
    status: 1,
  },
  {
    id: 2,
    sn: 'CH-2',
    name: '冷冻主机-2',
    model: 'CVHG780-489-287-T080S-800-T080L-800',
    position: '13区 2F ',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2006-07-10',
    status: 1,
  },
  {
    id: 3,
    sn: 'CH-3',
    name: '冷冻主机-3',
    model: 'CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0',
    position: '6-1区 GF层0-091',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2013年',
    status: 1,
  },
  {
    id: 4,
    sn: 'CH-4',
    name: '冷冻主机-4',
    model: 'CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0',
    position: '6-1区 GF层0-091',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2013年',
    status: 1,
  },
  {
    id: 5,
    sn: 'CH-5',
    name: '冷冻主机-5',
    model: 'CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0',
    position: '6-1区 GF层0-091',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2013年',
    status: 1,
  },
  {
    id: 6,
    sn: 'CH-6',
    name: '冷冻主机-6',
    model: 'CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0',
    position: '6-1区 GF层0-091',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2013年',
    status: 1,
  },
  {
    id: 7,
    sn: 'CH-7',
    name: '冷冻主机-7',
    model: 'CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0',
    position: '6-1区 GF层0-091',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2013年',
    status: 1,
  },
  {
    id: 8,
    sn: 'CHWP-01',
    name: '冷冻水泵-1',
    model: 'TD150-400',
    position: '13区 2F ',
    deviceTypeName: '冷冻水泵',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Elektrim',
    productDate: '2006年',
    status: 1,
  },
  {
    id: 9,
    sn: 'CH-1',
    name: '冷冻主机-1',
    model: 'CVHG780-489-287-T080S-800-T080L-800',
    position: '13区 2F ',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2006-07-10',
    status: 1,
  },
  {
    id: 10,
    sn: 'CH-2',
    name: '冷冻主机-2',
    model: 'CVHG780-489-287-T080S-800-T080L-800',
    position: '13区 2F ',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2006-07-10',
    status: 1,
  },
  {
    id: 11,
    sn: 'CH-3',
    name: '冷冻主机-3',
    model: 'CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0',
    position: '6-1区 GF层0-091',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2013年',
    status: 1,
  },
  {
    id: 12,
    sn: 'CH-4',
    name: '冷冻主机-4',
    model: 'CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0',
    position: '6-1区 GF层0-091',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2013年',
    status: 1,
  },
  {
    id: 13,
    sn: 'CH-5',
    name: '冷冻主机-5',
    model: 'CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0',
    position: '6-1区 GF层0-091',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2013年',
    status: 1,
  },
  {
    id: 14,
    sn: 'CH-6',
    name: '冷冻主机-6',
    model: 'CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0',
    position: '6-1区 GF层0-091',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2013年',
    status: 1,
  },
  {
    id: 15,
    sn: 'CH-7',
    name: '冷冻主机-7',
    model: 'CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0',
    position: '6-1区 GF层0-091',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2013年',
    status: 1,
  },
  {
    id: 16,
    sn: 'CHWP-01',
    name: '冷冻水泵-1',
    model: 'TD150-400',
    position: '13区 2F ',
    deviceTypeName: '冷冻水泵',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Elektrim',
    productDate: '2006年',
    status: 1,
  },
  {
    id: 17,
    sn: 'CH-1',
    name: '冷冻主机-1',
    model: 'CVHG780-489-287-T080S-800-T080L-800',
    position: '13区 2F ',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2006-07-10',
    status: 1,
  },
  {
    id: 18,
    sn: 'CH-2',
    name: '冷冻主机-2',
    model: 'CVHG780-489-287-T080S-800-T080L-800',
    position: '13区 2F ',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2006-07-10',
    status: 1,
  },
  {
    id: 19,
    sn: 'CH-3',
    name: '冷冻主机-3',
    model: 'CVGF1000TM0C67415101B1B1C1C49A10400E4NN0CN0T0',
    position: '6-1区 GF层0-091',
    deviceTypeName: '冷冻主机',
    systemName: '空调及机械通风系统',
    areaName: null,
    productFactory: 'Trane',
    productDate: '2013年',
    status: 1,
  },
];
const deviceKeepList = [
  {
    id: 1,
    name: '主机运行模式',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 0,
    option: '本控/中央控',
    unit: 'N/A',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 2,
    name: '设备状态',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 0,
    option: '运行/停止/故障',
    unit: 'N/A',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 3,
    name: '阀门运行模式',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 0,
    option: '手动/自动/关闭',
    unit: 'N/A',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 4,
    name: '当前冰水运行设定值',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: '℃',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 5,
    name: '电流',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: 'A',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 6,
    name: '电压',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: 'V',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 7,
    name: '压缩机运行RLA',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: '％',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 8,
    name: '运行功率',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: 'KW',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 9,
    name: '蒸发器进水温度',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: '℃',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 10,
    name: '蒸发器出水温度',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: '℃',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 11,
    name: '蒸发器冷媒饱和温度',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: '℃',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 12,
    name: '蒸发器冷媒压力',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: 'kPa',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 13,
    name: '冷凝器进水温度',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: '℃',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 14,
    name: '冷凝器出水温度',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: '℃',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 15,
    name: '冷凝器冷媒饱和温度',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: '℃',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
  {
    id: 16,
    name: '冷凝器冷媒趋近温度',
    systemName: '空调及机械通风系统',
    period: '1',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: '℃',
    standardDesc: null,
    imageUrl: null,
    remark: null,
  },
];
const deviceCheckList = [
  {
    id: 1,
    systemId: 1,
    deviceTypeId: 1,
    name: '设备状态',
    systemName: '空调及机械通风系统',
    period: '0',
    checkMethod: '目测',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 0,
    option: '运行/停止/故障',
    unit: 'N/A',
    standardDesc: null,
    imageUrl: null,
    remark: null,
    minValue: null,
    maxValue: null,
  },
  {
    id: 2,
    systemId: 1,
    deviceTypeId: 1,
    name: '主机运行模式',
    systemName: '空调及机械通风系统',
    period: '0',
    checkMethod: '记录设备显示',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 0,
    option: '本控/中央控',
    unit: 'N/A',
    standardDesc: null,
    imageUrl: null,
    remark: null,
    minValue: null,
    maxValue: null,
  },
  {
    id: 3,
    systemId: 1,
    deviceTypeId: 1,
    name: '阀门运行模式',
    systemName: '空调及机械通风系统',
    period: '0',
    checkMethod: '记录设备显示',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 0,
    option: '手动/自动/关闭',
    unit: 'N/A',
    standardDesc: null,
    imageUrl: null,
    remark: null,
    minValue: null,
    maxValue: null,
  },
  {
    id: 4,
    systemId: 1,
    deviceTypeId: 1,
    name: '当前冻水设定值',
    systemName: '空调及机械通风系统',
    period: '0',
    checkMethod: '记录设备显示',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: '℃',
    standardDesc: null,
    imageUrl: null,
    remark: null,
    minValue: null,
    maxValue: null,
  },
  {
    id: 5,
    systemId: 1,
    deviceTypeId: 1,
    name: '电压',
    systemName: '空调及机械通风系统',
    period: '0',
    checkMethod: '记录设备显示',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: 'V',
    standardDesc: null,
    imageUrl: null,
    remark: null,
    minValue: null,
    maxValue: null,
  },
  {
    id: 6,
    systemId: 1,
    deviceTypeId: 1,
    name: '电流-R',
    systemName: '空调及机械通风系统',
    period: '0',
    checkMethod: '记录设备显示',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: 'A',
    standardDesc: null,
    imageUrl: null,
    remark: null,
    minValue: null,
    maxValue: null,
  },
  {
    id: 7,
    systemId: 1,
    deviceTypeId: 1,
    name: '电流-S',
    systemName: '空调及机械通风系统',
    period: '0',
    checkMethod: '记录设备显示',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: 'A',
    standardDesc: null,
    imageUrl: null,
    remark: null,
    minValue: null,
    maxValue: null,
  },
  {
    id: 8,
    systemId: 1,
    deviceTypeId: 1,
    name: '电流-T',
    systemName: '空调及机械通风系统',
    period: '0',
    checkMethod: '记录设备显示',
    deviceTypeName: '冷冻主机',
    areaName: null,
    type: 1,
    option: null,
    unit: 'A',
    standardDesc: null,
    imageUrl: null,
    remark: null,
    minValue: null,
    maxValue: null,
  },
];
const deviceContextList = [
  {
    id: 37,
    systemId: null,
    deviceTypeId: null,
    name: '过滤器',
    specification: 'FLR01917',
    count: 0,
    totalInStockCount: 0,
    unit: '个',
    price: null,
    brand: null,
    lowerWarningStock: null,
    remark: null,
    createTime: null,
    updateTime: null,
    createBy: null,
    updateBy: null,
    systemName: '空调及机械通风系统',
    deviceTypeName: '冷冻主机',
  },
  {
    id: 127,
    systemId: null,
    deviceTypeId: null,
    name: '22',
    specification: '23',
    count: 23,
    totalInStockCount: 0,
    unit: null,
    price: 2,
    brand: null,
    lowerWarningStock: 2,
    remark: null,
    createTime: null,
    updateTime: null,
    createBy: null,
    updateBy: null,
    systemName: '空调及机械通风系统',
    deviceTypeName: '冷冻主机',
  },
  {
    id: 128,
    systemId: null,
    deviceTypeId: null,
    name: '过滤器',
    specification: null,
    count: 10,
    totalInStockCount: 0,
    unit: null,
    price: 1,
    brand: null,
    lowerWarningStock: 11,
    remark: null,
    createTime: null,
    updateTime: null,
    createBy: null,
    updateBy: null,
    systemName: '空调及机械通风系统',
    deviceTypeName: '冷冻主机',
  },
  {
    id: 38,
    systemId: null,
    deviceTypeId: null,
    name: '轴承',
    specification: null,
    count: 0,
    totalInStockCount: 0,
    unit: '个',
    price: null,
    brand: null,
    lowerWarningStock: null,
    remark: null,
    createTime: null,
    updateTime: null,
    createBy: null,
    updateBy: null,
    systemName: '空调及机械通风系统',
    deviceTypeName: '冷冻水泵',
  },
  {
    id: 39,
    systemId: null,
    deviceTypeId: null,
    name: 'O型密封圈',
    specification: null,
    count: 0,
    totalInStockCount: 0,
    unit: '套',
    price: null,
    brand: null,
    lowerWarningStock: null,
    remark: null,
    createTime: null,
    updateTime: null,
    createBy: null,
    updateBy: null,
    systemName: '空调及机械通风系统',
    deviceTypeName: '冷冻水泵',
  },
  {
    id: 40,
    systemId: null,
    deviceTypeId: null,
    name: '机械密封',
    specification: null,
    count: 0,
    totalInStockCount: 0,
    unit: '套',
    price: null,
    brand: null,
    lowerWarningStock: null,
    remark: null,
    createTime: null,
    updateTime: null,
    createBy: null,
    updateBy: null,
    systemName: '空调及机械通风系统',
    deviceTypeName: '冷冻水泵',
  },
  {
    id: 44,
    systemId: null,
    deviceTypeId: null,
    name: '良机LRC-H-900散热片（系统一）',
    specification: '0.35×320×800mm',
    count: 0,
    totalInStockCount: 0,
    unit: '片',
    price: null,
    brand: null,
    lowerWarningStock: null,
    remark: null,
    createTime: null,
    updateTime: null,
    createBy: null,
    updateBy: null,
    systemName: '空调及机械通风系统',
    deviceTypeName: '冷却水塔（系统一）',
  },
  {
    id: 45,
    systemId: null,
    deviceTypeId: null,
    name: '马利水塔NC8413 S-1散热片（系统二）',
    specification: '1524×3086×0.32mm',
    count: 0,
    totalInStockCount: 0,
    unit: '片',
    price: null,
    brand: null,
    lowerWarningStock: null,
    remark: null,
    createTime: null,
    updateTime: null,
    createBy: null,
    updateBy: null,
    systemName: '空调及机械通风系统',
    deviceTypeName: '冷却水塔（系统二）',
  },
];
const toolContextList = [
  {
    id: 1,
    name: '木工修边机',
    specification: 'MT370',
    count: 1,
    unit: '台',
    brand: null,
    remark: null,
    createTime: '2019-10-08 16:53:04',
    updateTime: null,
    createBy: null,
    updateBy: null,
  },
  {
    id: 2,
    name: '手电钻',
    specification: 'GBM10RE',
    count: 12,
    unit: '把',
    brand: null,
    remark: null,
    createTime: '2019-10-08 16:53:29',
    updateTime: '2019-10-15 14:43:45',
    createBy: null,
    updateBy: null,
  },
  {
    id: 3,
    name: '扳手',
    specification: 'GBM10RE',
    count: 12,
    unit: '把',
    brand: null,
    remark: null,
    createTime: '2019-10-08 16:53:29',
    updateTime: '2019-10-15 14:43:45',
    createBy: null,
    updateBy: null,
  },
];
export default {
  'GET /standing/deviceBasicList': deviceBasicList,
  'GET /standing/deviceCheckList': deviceCheckList,
  'GET /standing/deviceKeepList': deviceKeepList,
  'GET /standing/deviceContextList': deviceContextList,
  'GET /standing/toolContextList': toolContextList,
};
>>>>>>> 最终提交
